apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: chatbot-dev
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: php
        image: phpmyadmin:latest
        ports:
        - name: http
          containerPort: 80
        ports:
          - containerPort: 80
            name: https

        env:
          - name: PMA_HOST
            value: mysql-service
          - name: PMA_PORT
            value: "3306"
          #- name: DB_NAME
           # value: multitenancy
          - name: DB_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/os: windows


